person:
  name: klgentle${random.int}
  age: 18
  happy: true
  birthday: 2020/01/27
  maps: {k1: v1,k2: v2}
  hello: good morning
  lists:
    - music
    - code
    - girl
  dog:
    name: ${person.hello:hello} 旺财
    age: 1

dog:
  first-name: 阿白
  age: 2
